<?php
namespace Itxiao6\Framework\Facade\VarDumper;

class HtmlDumper extends \Symfony\Component\VarDumper\Dumper\HtmlDumper
{
    public function dumpLine($depth, $endOfValue = false)
    {
        $this -> headerIsDumped = false;
        parent::dumpLine($depth, $endOfValue); // TODO: Change the autogenerated stub
    }
}