<?php
namespace CloverSwoole\VarDumper;
use Symfony\Component\VarDumper\Cloner\Data;

/**
 * 每次打印都重置头部信息（重写父类方法dump）
 * Class HtmlDumper
 * @package CloverSwoole\CloverSwoole\Facade\VarDumper
 */
class HtmlDumper extends \Symfony\Component\VarDumper\Dumper\HtmlDumper
{
    /**
     * {@inheritdoc}
     */
    public function dump(Data $data, $output = null, array $extraDisplayOptions = array())
    {
        $this -> headerIsDumped = false;
        return parent::dump($data, $output, $extraDisplayOptions); // TODO: Change the autogenerated stub
    }
}