<?php
namespace Itxiao6\Framework\Facade\SwooleHttp\EasySwoole\Http;

use EasySwoole\Http\Request;
use EasySwoole\Http\Response;
use Illuminate\Container\Container;

class Controller extends \EasySwoole\Http\AbstractInterface\Controller
{
    /**
     * @var null|Container
     */
    protected $app = null;
    public function __hook(?string $actionName, Request $request, Response $response,?Container $container = null): void
    {
        $this -> app = $container;
        parent::__hook($actionName, $request, $response); // TODO: Change the autogenerated stub
    }

    public function index(){}
}